name: pyinterp
dependencies:
  - libboost-devel
  - cartopy>=0.20.0
  - cmake
  - coverage
  - dask
  - sphinx-book-theme
  - gtest
  - numcodecs
  - numpy
  - pandas
  - pip
  - pypandoc
  - pytest
  - lcov
  - pytest-cov
  - setuptools
  - sphinx-gallery
  - sphinx-inline-tabs
  - xarray
channels:
  - conda-forge
