name: pyinterp
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - cartopy
  - gcsfs
  - intake
  - intake-xarray
  - jupyter
  - numcodecs
  - pandas
  - pyinterp>=0.0
  - pytest
  - sphinx-gallery
  - sphinx-inline-tabs
